name: "Check line width"
on: [push, pull_request]
jobs:
  # line-number:
  #   name: Sloc < 1000
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - run: cargo install tokei
  #     - run: num_sloc=$(tokei --type=Lua,'Vim script' --output=json . | jq .Total.code); if [ ${num_sloc} -gt 999 ]; then exit 1; fi

  line-width:
    name: Line width < 80 characters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cargo install --locked ripgrep
      - run: max_line_width=$(rg --glob '*.{lua,vim}' --no-heading --no-filename --no-line-number . | awk '{print length}' | sort -n | tail -n 1); if [ ${max_line_width} -gt 79 ]; then exit 1; fi
